build-and-publish-head:
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/develop' # Running this job only for develop branch

  steps:
    - uses: actions/checkout@v2 # Checking out the repo

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.1.12
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
        image-name: test-service # Provide Docker image name
        image-tag: head # Provide Docker image tag
